### ISSUE TITLE
Preliminary Code for Motor Control

### ISSUE THREAD

**Issue by CharloLeRigolo** [CharloLeRigolo/arm_us#3]

**Comment by Pmichaud29** [comment]
mikael 2.5 hrs
Philippe 6.5 hrs

**Comment by Pmichaud29** [comment]
Requirements : 
- 2 XL430
- Ctrl : id3 with Left Joystick and id9 with Right One
- CtrlMode : Velocity mapped on joystick from 0 t max rad/s
