### ISSUE TITLE
Preleminary Shoulder conception

### ISSUE THREAD

**Issue by CharloLeRigolo** [CharloLeRigolo/arm_us#7]

**Comment by CharloLeRigolo** [comment]
First  version of SolidWork Assembly of the shoulder done

**Comment by CharloLeRigolo** [comment]
reprint of some pieces

**Comment by Pmichaud29** [comment]
Cadded motor to 6mm shaft coupling adapter

Heures : 
0.5h

**Comment by CharloLeRigolo** [comment]
New Print Started 
H: 0,5h
